tunnel: ${CLOUDFLARED_TUNNEL_NAME}
credentials-file: ${CLOUDFLARED_CREDENTIALS_FILE}

ingress:
  - hostname: ${CLOUDFLARED_HOSTNAME}
    service: ${CLOUDFLARED_SERVICE}
    originRequest:
      noTLSVerify: true

  - service: http_status:404
